### ISSUE TITLE
Calendar dot indicator from previous month not showing 

### ISSUE THREAD

**Issue by hellodommy** [AY1920S1-CS2103T-T12-3/main#136]
![image](https://user-images.githubusercontent.com/47271661/67956952-d8a70e00-fc2f-11e9-80a2-6973d758e8ee.png)
![image](https://user-images.githubusercontent.com/47271661/67956969-df358580-fc2f-11e9-9949-5dd4bc7d2a5e.png)

Notice in the screenshots that 2 Sep has a dot in August, but no dot in September view.

**Comment by shawnlsj97** [comment]
Haha didnt do anything and it seems to have fixed itself
