### ISSUE TITLE
7.1: Update project website: AboutUs, ContactUs, README

### ISSUE THREAD

**Issue by hellodommy** [AY1920S1-CS2103T-T12-3/main#5]
**[Step 1](https://nus-cs2103-ay1920s1.github.io/website/schedule/week7/project.html#1-update-project-website-aboutus-contactus-readme) of Week 7 increments:**

- [x] Photos from all developers for _About Us_ page
- [x] Assign roles and responsibilities for all developers
- [x] Assign email for _Contact Us_ page
- [x] Create UI mockup of intended final product @hellodommy 
- [x] Restructure `README.adoc` to look like the home page of a real product @shawnlsj97 
- [x] Update Travis _build status badge_ to reflect build status of team repo
- [x] Update/remove other badges as well @hellodommy 
- [x] Acknowledge original source of code at `https://se-education.org` @shawnlsj97 
- [x] Update website heading to match product @shawnlsj97

**Comment by hellodommy** [comment]
- Will add Coveralls later

- Not setting up Gitter

**Comment by hellodommy** [comment]
Not setting up Gitter for Athletick

**Comment by shawnlsj97** [comment]
All tasks completed
